[package]
name = "pepper"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1.7"
chumsky = { version = "1.0.0-alpha.7", features = ["label"] }
clap = { version = "4.5.8", features = ["derive"] }
codespan-reporting = "0.11.1"
cranelift = { version = "0.109.0", features = ["module", "object"] }
ordered-float = "4.2.1"
owo-colors = "4.0.0"
rustc-hash = "2.0.0"
salsa = { git = "https://github.com/salsa-rs/salsa.git", rev = "a1bf3a6" }
serde = { version = "1.0.204", features = ["derive"] }
target-lexicon = "0.12.15"
toml = "0.8.14"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
alloc_instead_of_core = "warn"
std_instead_of_core = "warn"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
unused_unit = "allow"
used_underscore_binding = "allow"
